# Generated by Django 4.2.4 on 2023-08-22 00:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('surname', models.CharField(max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='Ganre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganre', models.CharField(max_length=23)),
                ('avarage_rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('surname', models.CharField(max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(auto_created=True, editable=False, max_length=72)),
                ('label', models.CharField(default='Unknown Film', max_length=23)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('image', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('actor', models.ManyToManyField(to='app.actor')),
                ('ganre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ganre')),
                ('produser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.producer')),
            ],
        ),
    ]
